apiVersion: v1
kind: Service
metadata:
  name: vllm-fork-with-llama-2-7b-chat-hf-service
  labels:
    name: vllm-fork-with-llama-2-7b-chat-hf
spec:
  type: ClusterIP
  selector:
    name: vllm-fork-with-llama-2-7b-chat-hf
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

